export const ADD_ARTICLE = "ADD_ARTICLE";
export const REMOVE_ARTICLE = "REMOVE_ARTICLE";
export const LIKE_ARTICLE = "LIKE_ARTICLE";
export const ADD_TO_COUNTER = "ADD_TO_COUNTER";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_OUT_USER = "LOG_OUT_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const UPDATE_AUTH = "UPDATE_AUTH";

//MEETUP
export const MEETUP_HAS_ERRORED = "MEETUP_HAS_ERRORED";
export const MEETUP_FETCH_DATA_SUCCESS = "MEETUP_FETCH_DATA_SUCCESS";
export const MEETUP_IS_LOADING = "MEETUP_IS_LOADING";

//MEETUPS
export const MEETUPS_HAS_ERRORED = "MEETUPS_HAS_ERRORED";
export const MEETUPS_FETCH_DATA_SUCCESS = "MEETUPS_FETCH_DATA_SUCCESS";
export const MEETUPS_IS_LOADING = "MEETUPS_IS_LOADING";


export const MESSAGES_FETCH_DATA_SUCCESS = "MESSAGES_FETCH_DATA_SUCCESS";
